name: tyssue
channels:
- conda-forge

dependencies:
- python=3.10
- pip
- numpy
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
- quantities
- ipython
- ipython_genutils
- ipywidgets
- pythreejs
- ipyvolume
- vispy
- meshio
- zarr
- xarray
